#!/usr/bin/env python3
"""Render the hand-written pages of the lmflow documentation site.

Usage::

    python docs/web/build.py [output-dir]      # default output dir: site

Turns the Markdown sources next to this script (plus the design document) into
standalone HTML pages using the shared template, and lays out the directories
that the *generated* API docs are copied into afterwards:

    <out>/            index.html + stylesheets      (this script)
    <out>/cpp/        C / C++ guide                 (this script)
    <out>/design/     design document (Chinese)     (this script)
    <out>/rust/       redirect shell only           (this script)
                      ... then `cargo doc` output is copied in on top
    <out>/python/                                   (pdoc writes it directly)

Dependencies: ``markdown2`` and ``pygments``, both of which ship as pdoc
dependencies -- the docs workflow installs pdoc anyway, so this adds nothing.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import markdown2
from pygments.formatters import HtmlFormatter

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]  # docs/web -> docs -> repo root

REPO_URL = "https://github.com/laomou/lm-flow"

# markdown2 扩展:围栏代码块(带 pygments 高亮)、表格、标题锚点、目录。
# code-friendly 关掉 `_` 的强调语义 —— 这是代码密集文档的必需项(`snake_case`
# 里的下划线不该变成斜体)。
EXTRAS = {
    "fenced-code-blocks": {},
    "tables": None,
    "header-ids": None,
    "code-friendly": None,
    "cuddled-lists": None,
    "toc": {"depth": 3},
}

# 顶栏导航:(key, 显示名, 相对站点根的路径)
NAV = [
    ("home", "Home", ""),
    ("rust", "Rust API", "rust/"),
    ("cpp", "C / C++", "cpp/"),
    ("python", "Python API", "python/"),
    ("design", "Design (中文)", "design/"),
]

# 要渲染的页面:(源文件, 输出路径, <title>, 导航高亮 key, lang, 是否出目录)
PAGES = [
    (
        ROOT / "docs/web/index.md",
        "index.html",
        "lmflow — dataflow-graph engine",
        "home",
        "en",
        False,
        "A dataflow-graph compute engine: a Rust scheduler behind a stable C ABI, "
        "with kernels in Rust, C++ or Python.",
    ),
    (
        ROOT / "docs/web/cpp.md",
        "cpp/index.html",
        "C / C++ API — lmflow",
        "cpp",
        "en",
        True,
        "Using the lmflow engine from C and C++: the stable C ABI, the flow.hpp "
        "kernel sugar layer, and how to embed the static library.",
    ),
    (
        ROOT / "docs/design.md",
        "design/index.html",
        "设计方案 — lmflow",
        "design",
        "zh",
        True,
        "lmflow 引擎的权威设计文档(中文):调度、时间戳、锁序、ADR 决策记录。",
    ),
]

# `cargo doc` 的产出根目录里没有 index.html(真入口是 lmflow/index.html),
# 所以这里放一个重定向壳。rustdoc 拷贝步骤只往这个目录里加文件,不会覆盖它。
RUST_REDIRECT = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Rust API — lmflow</title>
<meta http-equiv="refresh" content="0; url=lmflow/index.html">
<link rel="canonical" href="lmflow/index.html">
</head>
<body>
<p>Redirecting to the <a href="lmflow/index.html">lmflow crate documentation</a>&hellip;</p>
</body>
</html>
"""


def render_nav(active: str, root: str) -> str:
    """Build the top-bar links, marking `active` and resolving paths against `root`."""
    out = []
    for key, label, path in NAV:
        cls = ' class="active"' if key == active else ""
        out.append(f'<a href="{root}{path}"{cls}>{label}</a>')
    out.append(f'<a href="{REPO_URL}">GitHub</a>')
    return "\n    ".join(out)


def highlight_css() -> str:
    """Pygments token colours for both colour schemes.

    The bare `.codehilite` rule (which only sets a background) is dropped so the
    stylesheet's own `pre` background stays in charge -- otherwise the light
    theme's background would leak into dark mode.
    """

    def defs(style: str) -> str:
        raw = HtmlFormatter(style=style).get_style_defs(".codehilite")
        keep = [ln for ln in raw.splitlines() if not ln.startswith(".codehilite {")]
        return "\n".join(keep)

    light = defs("default")
    try:
        dark_raw = defs("github-dark")
    except Exception:  # 老版本 pygments 没有 github-dark,退回 monokai
        dark_raw = defs("monokai")
    dark = "\n".join("  " + ln for ln in dark_raw.splitlines())
    return (
        "/* Generated by docs/web/build.py -- do not edit. */\n"
        f"{light}\n\n@media (prefers-color-scheme: dark) {{\n{dark}\n}}\n"
    )


def build(out_dir: Path) -> None:
    template = (HERE / "template.html").read_text(encoding="utf-8")

    # 全量重建:否则本地反复跑时,删掉的页面会以旧产物的形式留在站点里。
    shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(HERE / "style.css", out_dir / "style.css")
    (out_dir / "highlight.css").write_text(highlight_css(), encoding="utf-8")

    for src, rel_out, title, active, lang, want_toc, description in PAGES:
        if not src.exists():
            raise SystemExit(f"build.py: missing source page: {src}")

        html = markdown2.markdown(src.read_text(encoding="utf-8"), extras=EXTRAS)

        toc = ""
        if want_toc and getattr(html, "toc_html", None):
            toc = (
                '<details class="toc">\n<summary>Contents</summary>\n'
                f"{html.toc_html}</details>"
            )

        # 深度 1 的页面(cpp/ design/)要用 ../ 回到站点根
        root = "../" if "/" in rel_out else "./"
        page = (
            template.replace("{{lang}}", lang)
            .replace("{{title}}", title)
            .replace("{{description}}", description)
            .replace("{{root}}", root)
            .replace("{{nav}}", render_nav(active, root))
            .replace("{{toc}}", toc)
            .replace("{{content}}", str(html))
        )

        dest = out_dir / rel_out
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(page, encoding="utf-8")
        print(f"  {src.relative_to(ROOT)} -> {dest.relative_to(out_dir.parent)}")

    rust_dir = out_dir / "rust"
    rust_dir.mkdir(parents=True, exist_ok=True)
    (rust_dir / "index.html").write_text(RUST_REDIRECT, encoding="utf-8")
    print(f"  (redirect shell) -> {(rust_dir / 'index.html').relative_to(out_dir.parent)}")


def main() -> None:
    out_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "site").resolve()
    print(f"building lmflow docs site into {out_dir}")
    build(out_dir)
    print("done. `cargo doc` output goes into rust/, pdoc output into python/.")


if __name__ == "__main__":
    main()
