from dataclasses import dataclass
from typing import Any, AsyncIterator, Callable, Sequence

class Packet:
    timestamp: int
    is_empty: bool
    type_id: int
    type_name: str
    def as_int(self) -> int | None: ...
    def as_float(self) -> float | None: ...
    def as_bool(self) -> bool | None: ...
    def as_str(self) -> str | None: ...
    def as_bytes(self) -> bytes | None: ...
    def as_numpy(self) -> Any: ...
    def make_mutable(self) -> Any: ...
    @staticmethod
    def from_int(value: int, ts: int = ...) -> Packet: ...
    @staticmethod
    def from_float(value: float, ts: int = ...) -> Packet: ...
    @staticmethod
    def from_bool(value: bool, ts: int = ...) -> Packet: ...
    @staticmethod
    def from_str(value: str, ts: int = ...) -> Packet: ...
    @staticmethod
    def from_bytes(value: bytes, ts: int = ...) -> Packet: ...

class Contract:
    num_inputs: int
    num_outputs: int
    def input_id(self, tag: str, index: int = ...) -> int: ...
    def output_id(self, tag: str, index: int = ...) -> int: ...
    def input_name(self, index: int) -> str: ...
    def output_name(self, index: int) -> str: ...
    def input_set_any(self, index: int) -> None: ...
    def output_set_any(self, index: int) -> None: ...
    def input_set_type(self, index: int, type_id: int) -> None: ...
    def output_set_type(self, index: int, type_id: int) -> None: ...
    def require_side_packet(self, name: str) -> None: ...

class Context:
    num_inputs: int
    num_outputs: int
    node_name: str
    kernel_name: str
    close_reason: int
    input_timestamp: int
    def input_id(self, tag: str, index: int = ...) -> int: ...
    def output_id(self, tag: str, index: int = ...) -> int: ...
    def input_index(self, name: str) -> int: ...
    def input_name(self, index: int) -> str: ...
    def output_name(self, index: int) -> str: ...
    def input_is_empty(self, index: int) -> bool: ...
    def input_is_done(self, index: int) -> bool: ...
    def input(self, index: int) -> Packet | None: ...
    def input_count(self, index: int) -> int: ...
    def input_at(self, index: int, k: int) -> Packet | None: ...
    def take_input(self, index: int) -> Packet | None: ...
    def emit(self, index: int, value: Any, ts: int | None = ...) -> None: ...
    def forward(self, in_index: int, out_index: int) -> None: ...
    def set_next_timestamp_bound(self, timestamp: int) -> None: ...
    def new_buffer(self, shape: Sequence[int], dtype: str) -> tuple[Packet, Any]: ...
    def has_option(self, key: str) -> bool: ...
    def option_int(self, key: str, default: int = ...) -> int: ...
    def option_float(self, key: str, default: float = ...) -> float: ...
    def option_bool(self, key: str, default: bool = ...) -> bool: ...
    def option_str(self, key: str, default: str = ...) -> str: ...
    def options_json(self) -> str: ...
    def require_option_int(self, key: str) -> int: ...
    def require_option_float(self, key: str) -> float: ...
    def require_option_str(self, key: str) -> str: ...
    def has_side_packet(self, name: str) -> bool: ...
    def side_packet(self, name: str) -> Packet | None: ...
    def log(self, level: int, msg: str) -> None: ...
    def set_error(self, msg: str) -> None: ...
    def source_done(self) -> None: ...
    def source_yield(self, delay_seconds: float = ...) -> None: ...
    def counter_add(self, name: str, delta: int = ...) -> None: ...

class Kernel:
    def get_contract(self, c: Contract) -> None: ...
    def open(self, cc: Context) -> None: ...
    def process(self, cc: Context) -> None: ...
    def close(self, cc: Context) -> None: ...

def kernel(name: str) -> Callable[[type[Kernel]], type[Kernel]]: ...

class Input:
    def send(self, value: Any, ts: int | None = ...) -> None: ...
    def try_send(self, value: Any, ts: int | None = ...) -> bool: ...
    def close(self) -> None: ...

class Poller:
    def next(self, timeout: float | None = ...) -> Packet | None: ...
    def try_next(self) -> Packet | None: ...

class KernelRunner:
    """Single-kernel test harness; directly drives one kernel without Graph."""
    def __init__(
        self,
        kernel: str,
        input_ports: int = ...,
        output_ports: int = ...,
        options: Any = ...,
        side_packets: dict[str, Any] = ...,
    ) -> None: ...
    def __enter__(self) -> KernelRunner: ...
    def __exit__(self, *args: object) -> None: ...
    def start(self) -> None: ...
    def add_input(self, port: int, value: Any, ts: int | None = ...) -> None: ...
    def process(self, timestamp: int) -> None: ...
    def try_next(self, port: int = ...) -> Packet | None: ...
    def close(self) -> None: ...

class LogLevel:
    ERROR: int
    WARN: int
    INFO: int
    DEBUG: int

class CloseReason:
    NORMAL: int
    ERROR: int
    CANCELLED: int

class GraphState:
    CREATED: int
    INITIALIZED: int
    RUNNING: int
    DRAINING: int
    TERMINATED: int

class DotView:
    TOPOLOGY: str
    COMPACT: str
    DIAGNOSTICS: str

class OutputEvent: ...

@dataclass(frozen=True)
class PacketEvent(OutputEvent):
    packet: Packet
    @property
    def timestamp(self) -> int: ...

@dataclass(frozen=True)
class TimestampBoundEvent(OutputEvent):
    timestamp: int

@dataclass(frozen=True)
class DoneEvent(OutputEvent):
    timestamp: int = ...

class AsyncOutputEvents(AsyncIterator[OutputEvent]):
    def __init__(self, graph: Graph, poller: Poller) -> None: ...
    def __aiter__(self) -> AsyncOutputEvents: ...
    async def __anext__(self) -> OutputEvent: ...

class Graph:
    def __init__(self) -> None: ...
    @classmethod
    def from_yaml(cls, yaml: str) -> Graph: ...
    @classmethod
    def from_yaml_file(cls, path: str) -> Graph: ...
    def input(self, port: str) -> Input: ...
    def add_poller(self, port: str, observe_timestamp_bounds: bool = ...) -> Poller: ...
    def events(self, port: str) -> AsyncOutputEvents: ...
    def observe(
        self,
        port: str,
        fn: Callable[[Packet], Any],
        *,
        observe_timestamp_bounds: bool = ...,
    ) -> None: ...
    def start(self) -> None: ...
    def reset(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def send(self, port: str, value: Any, ts: int | None = ...) -> None: ...
    def close_input(self, port: str) -> None: ...
    def close_all_inputs(self) -> None: ...
    def wait_done(self, timeout: float | None = ...) -> None: ...
    def wait_until_idle(self, timeout: float | None = ...) -> None: ...
    async def run_async(
        self, *, timeout: float | None = ..., cancel_grace: float = ...
    ) -> None: ...
    def pump_step(self) -> bool: ...
    def pump_steps(self, max_steps: int) -> int: ...
    def set_side_packet(self, name: str, value: Any) -> None: ...
    def new_buffer(self, shape: Sequence[int], dtype: Any) -> tuple[Packet, Any]: ...
    def cancel(self) -> None: ...
    @property
    def state(self) -> int: ...
    def last_error(self) -> str: ...
    def dropped_count(self, port: str) -> int: ...
    def counter_value(self, name: str) -> int: ...
    def to_dot(self, view: str = ...) -> str: ...
    def to_chrome_trace(self) -> str: ...
    def close(self) -> None: ...

class Timeout(TimeoutError): ...
class KernelError(RuntimeError): ...

def has_cv_test_kernels() -> bool: ...
def register_cv_test_kernels() -> None: ...
def set_log_callback(fn: Callable[[int, str], Any] | None) -> None: ...
def type_name(type_id: int) -> str: ...
def type_id(stable_name: str) -> int: ...

INVALID_ID: int
ABI_VERSION: int
TS_UNSET: int
TS_PRE_STREAM: int
TS_POST_STREAM: int
TS_DONE: int
